### ISSUE TITLE
Simplify CSS code for shared properties.

### ISSUE THREAD

**Issue by josephtkim** [kristysk/prj-rev-bwfs-dasmoto#5]
It is a good idea to try and simplify the CSS code to make the code cleaner and to remove repetitive code. There are a few properties that are shared, which you can simplify like the font-family and font-weight properties. You might simplify it like so by applying them to multiple selectors at once

```css
#header, .section, .price {
    font-family: Helvetica;
    font-weight: bold;
}
```
